language: cpp

git:
    depth: 3

matrix:
  include:
  - os: linux
    env: NAME="Ubuntu Linux (Latest)" NAME_SUFFIX="ubuntu"
    services: docker
    script:
      - git submodule init && git submodule update
      - scripts/docker/docker_travis.sh "ubuntu_latest.docker"
  - os: linux
    env: NAME="Fedora Linux (Latest)" NAME_SUFFIX="fedora"
    services: docker
    script:
      - git submodule init && git submodule update
      - scripts/docker/docker_travis.sh "fedora_latest.docker"
  - os: linux
    env: NAME="Arch Linux (Latest)" NAME_SUFFIX="arch" DEBUG=1
    services: docker
    script:
      - git submodule init && git submodule update
      - scripts/docker/docker_travis.sh "arch_latest.docker"
  - os: linux
    env: NAME="conan" NAME_SUFFIX="conan" USE_CONAN=1
    script:
      - scripts/docker/docker_travis.sh "conan_base.docker"
  - os: osx
    env: NAME="Apple macOS" NAME_SUFFIX="mac"
    osx_image: xcode9.4
    install:
      - git submodule init && git submodule update
      - brew update
      - /usr/bin/yes | pip2 uninstall numpy  # see https://github.com/travis-ci/travis-ci/issues/6688
      - brew upgrade python
      - brew upgrade
      - brew install boost cmake bullet ffmpeg glm openal-soft qt5 sdl2 jack freetype
      - export PATH="/usr/local/opt/qt/bin:$PATH"
    script:
      - mkdir -p "$TRAVIS_BUILD_DIR/build"
      - ctest -VV -S "$TRAVIS_BUILD_DIR/cmake/ctest/script_ci.ctest"

notifications:
    email: false
#    irc:
#        channels:
#            - chat.freenode.net#openrw
#        template:
#            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
